version: '3.9'
services:
  # Faux
  faux:
      container_name: faux
      image: node:16.6.0-alpine3.13
      volumes:
          - .:/home/app
          - /home/app/node_modules
      working_dir: /home/app
      command: tail -F anything